### ISSUE TITLE
How to initialize scripts that rely on values from the window. i.e Fullstory

### ISSUE THREAD

**Issue by Legym** [BuilderIO/partytown#79] opened 2022-02-16 01:45 UTC
This library is awesome. Thanks for all the hard work!

I am using NextJs for my application and I am trying to load [Fullstory](https://www.fullstory.com/) onto my site. However I'm unable to get the script to load. This is my file.

```
import { Partytown } from '@builder.io/partytown/react';

<Head>
     <Partytown />
     
        <script
            type="text/partytown"
            dangerouslySetInnerHTML={{
              __html: `
              window['_fs_debug'] = false;
              window['_fs_host'] = 'fullstory.com';
              window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
              window['_fs_org'] = 'XXX';
              window['_fs_namespace'] = 'FS';
              (function(m,n,e,t,l,o,g,y){
                  if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
                  g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
                  o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
                  y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
                  g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
                  g.anonymize=function(){g.identify(!!0)};
                  g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
                  g.log = function(a,b){g("log",[a,b])};
                  g.consent=function(a){g("consent",!arguments.length||a)};
                  g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
                  g.clearUserCookie=function(){};
                  g.setVars=function(n, p){g('setVars',[n,p]);};
                  g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
                  if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
                  g._v="1.3.0";
              })(window,document,window['_fs_namespace'],'script','user');
              `,
            }}
          ></script>
</Head>

```
I've tried adding the forward properties as well, but no luck.

`<Partytown forward={['_fs_debug', '_fs_host', '_fs_script', '_fs_org', '_fs_namespace']}`

If anyone has implemented FS, i'd love to understand what im doing wrong. This is my console to hopefully add any more information.  Thank you!

![image](https://user-images.githubusercontent.com/4462368/154180359-5710bc51-f3d7-4386-bc9f-9c87dfeb0793.png)

**Comment by Legym** [comment] 2022-02-16 16:26
After digging more into it, I have a theory. 

The script i originally posted downloads a JS file from https://edge.fullstory.com/s/fs.js. Looking into the code, it reads values from the window. If i understand this correctly, the web worker does not have access to the main threads window which means when the script is being initialized the values ive defined are null.

If this is the case, is there a way to pass values from the window into the web worker? 

If i'm unable to, then the only way i can think of is to self host https://edge.fullstory.com/s/fs.js and do a find/replace on portions that reference my global variables

**Comment by adamdbradley** [comment] 2023-03-21 14:51
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 14:51 UTC
Labels: help wanted
