### ISSUE TITLE
Usage with constent management platform like Didomi

### ISSUE THREAD

**Issue by niksy** [BuilderIO/partytown#82] opened 2022-02-17 14:35 UTC
Since Partytown uses custom `script` element `type` attribute to collect all code which should be handled by Partytown, this can clash with recommendation from CMPs like Didomi which also [use custom `type` attribute value to evaulate code](https://developers.didomi.io/cmp/web-sdk/third-parties/custom-integrations/no-tag-manager) which will be handled differently than classic approach and in control of Didomi.

What is your recommendation on how to handle these cases? Should this code be double wrapped, Partytown at the top?

**Comment by Tomas2D** [comment] 2022-10-11 21:42
Have you manage to solve this? @niksy

**Comment by niksy** [comment] 2022-10-12 07:27
No, still looking for guidance from maintainers.

**Comment by adamdbradley** [comment] 2023-03-21 14:49
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 14:49 UTC
Labels: help wanted, question
