### ISSUE TITLE
Using partytown inside js file.

### ISSUE THREAD

**Issue by rohit0122** [BuilderIO/partytown#300] opened 2022-11-14 15:25 UTC
**Is your feature request related to a problem? Please describe.**
In our current project architecture(which is very huge & complex), we have very large number of JS files and code base inside it.
We are able to integrate party town using script tags, but those are limited to html files(script type="text/partytown") only.

Now, we need to implement partytown inside the JS files also, not all code need to be in partytown, but some of the code should be wrap with partytown in most of the JS files. But, I am unable to find any right way of doing this.

**Describe the solution you'd like**
Like in html files, we can wrap the required JS code using script type="text/partytown", and its working fine.

Similarly, in-order to use the  partytown features, I am looking for a solution where we can wrap required JS code that is present inside the javascript file.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by adamdbradley** [comment] 2023-03-21 15:21
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 15:21 UTC
