### ISSUE TITLE
[🐞] Google Tag Assistant Preview is not showing tags (Google Tag Manager) while using Partytown

### ISSUE THREAD

**Issue by maruthasalamr** [BuilderIO/partytown#559] opened 2024-02-20 08:26 UTC
### Describe the bug

I need to test the events are triggered from my website in Google Tag manager. In GTM preview mode i cannot able to see any events and it says like no tags found.

This the party town implementation code

 <Partytown debug={true} forward={['dataLayer.push']}>
        <script type="text/partytown">{`
         (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
         new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
         j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
         'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
         })(window,document,'script','dataLayer','GTM-MKPX3TV4')
        `}</script>
       </Partytown>

<img width="902" alt="image" src="https://github.com/BuilderIO/partytown/assets/78694065/1c5588d3-a14b-42b0-a19e-ab8746f1f3ac">

### Reproduction

None

### Steps to reproduce

Add the partytown in the script tag of GTM in Head component
connect to the localhost to google tag assistant 

### Browser Info

Chrome

**Comment by j0Shi82** [comment] 2024-02-20 12:42
duplicate of #72

**Closed** 2024-02-24 10:47 UTC
Labels: bug
