### ISSUE TITLE
[Question] Is it possible to use together with GoogleMaps (or googlemaps/js-api-loader)?

### ISSUE THREAD

**Issue by Sin1tar** [BuilderIO/partytown#77] opened 2022-02-15 15:11 UTC
Hello, thanks for this perfect library!

So, almost every library for any framework uses [googlemaps/js-api-loader](https://github.com/googlemaps/js-api-loader) "under the hood".

Can we somehow make it work along with Partytown?

Examples:
[googlemaps/react-wrapper](https://github.com/googlemaps/react-wrapper)
[google-map-react](https://github.com/google-map-react/google-map-react)
[vue3-google-map](https://github.com/inocan-group/vue3-google-map)
etc

**Comment by adamdbradley** [comment] 2023-03-21 14:49
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 14:49 UTC
Labels: help wanted, question
