### ISSUE TITLE
Bing integration: UET is not a constructor

### ISSUE THREAD

**Issue by dbashford** [BuilderIO/partytown#106] opened 2022-03-09 20:26 UTC
https://bat.bing.com/bat.js

That includes at the start of it a `UET`.

partytown seems to yank it in, but then fails with UET is not a constructor. Let me know if there's anything I can do to assist/troubleshoot.

Using 0.4.5. Tried adding `UET` to the forward config and that didn't do anything for me.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/581127/157529788-2572cca7-bf28-423c-a7ce-c5873a27d7c8.png">

**Comment by MananTank** [comment] 2022-03-16 06:27
We are also facing the same issue

Root cause of this error is that currently, globally declared function in one partytown script can not be used in other partytown script.

Refer to this simplified [Example](https://vpxcwd.csb.app/)
sandbox : https://codesandbox.io/s/partytown-global-functions-vpxcwd

![image](https://user-images.githubusercontent.com/22043396/158529138-4078a520-6b55-4bde-a896-616c1b4161c5.png)

CC @adamdbradley

**Comment by tarponjargon** [comment] 2022-03-17 23:53
For completeness' sake, I tried forwarding all the objects bing adds to the window, got same `UET is not a constructor` error

`forward: ['uetq.push', 'uetq', 'UET', 'UET_init', 'UET_push'],`

**Comment by tolgacesur** [comment] 2022-03-22 07:45
Hi, is there any update on this issue? We have the same issue with Facebook and Twitter scripts. It doesn't seem script related issue. as @MananTank says scripts that are in service workers can't use global variables which are created from another script.

<img width="1191" alt="fbq and twttr" src="https://user-images.githubusercontent.com/17507470/159431707-f2fbb764-23bf-4fa6-9afa-c7f1d95ca073.png">

with the 0.3.5 version, it works. After the 0.4.0 version, this problem appears. maybe it helps

**Comment by adamdbradley** [comment] 2022-03-23 21:18
Thanks @tolgacesur, you're right, this is directly related to https://github.com/BuilderIO/partytown/issues/114 

Currently there is an undocumented `globalFns` config, but not sure if we'll go with that solution yet.

Will close this issue since https://github.com/BuilderIO/partytown/issues/114 should solve this.

Also @tolgacesur, would you be able to open another issue in regards to https://github.com/BuilderIO/partytown/issues/106#issuecomment-1074837672 Thanks

**Closed by adamdbradley** 2022-03-23 21:18 UTC
