### ISSUE TITLE
Support for Google Tag Manager Community Templates (Sandboxed JS)

### ISSUE THREAD

**Issue by klunejko** [BuilderIO/partytown#80] opened 2022-02-16 18:20 UTC
I tried converting our existing GTM setup to run through partytown, however I ran into issues with the majority of our tags. Official templates worked as expected (Google Adwords, Analytics etc.), as do Custom HTML/Image tags. The problem is with Community Templates which are already sandboxed by GTM. Functionality isn't affected (these tags can still inject scripts), however window variables aren't being forwarded from GTM to the sandboxed tag:

```
partytown = {
  forward: [ 
    'dataLayer.push', 'fbq' 
  ] 
};
```
This works fine and fbq can be accessed if the fb pixel is included directly on the page or via GTM using the Custom HTML tag.

Same goes for dataLayer variables that are set when configuring the template.

Code within GTM Template
```
// data.value = dataLayer.ecommerce.value (forwarded from partytown)
const value = data.value; // works

// sandbox within a sandbox
let fbq = copyFromWindow('fbq'); // This is where it breaks down
```

I couldn't find details regarding the sandbox implementation that GTM uses, so I'm not sure if this is something that can be solved or not. Alternatively we could always rewrite the templates as custom html tags, though ideally I would like to avoid having duplicate tags instead of a single template.

Info regarding the sandbox can be found here:
https://developers.google.com/tag-platform/tag-manager/templates/sandboxed-javascript

Thanks in advance.

**Comment by steve8708** [comment] 2022-05-28 19:30
hey @klunejko  - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Partytown version**
What version of Partytown you are using, e.g. `0.0.1`

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by adamdbradley** [comment] 2023-03-21 14:59
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 14:59 UTC
Labels: enhancement, help wanted
