### ISSUE TITLE
[🐞] CORS error while integrating google adsense

### ISSUE THREAD

**Issue by harshit-kathuria** [BuilderIO/partytown#535] opened 2024-01-18 10:40 UTC
### Describe the bug

Integratingg `Google Adsense` to Partytown, throws CORS error. Works fine running it directly in main thread. As both run on the same domain, why is this happening.

Framework: Sveltekit

File: route/layout.svelte

```
let scriptEl
  onMount(async () => {
    if (scriptEl) {
      scriptEl.textContent = partytownSnippet()
    }
   .......
}

<svelte:head>
  <script>
    // Forward the necessary functions to the web worker layer
		partytown = {
      forward: ['dataLayer.push'],
    }
    </script>
  <script bind:this={scriptEl}></script>
  <script type="text/partytown" src="https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXXX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("event", "gtm.js");
    gtag("gtm.start", new Date().getTime());
    gtag("gtm.uniqueEventId", 0);
  </script>
  <script type="text/partytown" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXXXXXX" crossorigin="anonymous">
  </script>
</svelte:head>
```

### Reproduction

NA

### Steps to reproduce

Add Google adsense script

### Browser Info

Chrome, Safari, Firefox

**Comment by gioboa** [comment] 2024-01-19 06:36
Thanks for reporting this issue. It's really odd, did you try with a proxy?

**Comment by gioboa** [comment] 2024-01-19 06:46
This is a duplicate of #360.
Let's continue the issue there. Thanks

**Closed by gioboa** 2024-01-19 06:46 UTC
Labels: bug
