### ISSUE TITLE
Question postMessage

### ISSUE THREAD

**Issue by stephenjason89** [BuilderIO/partytown#281] opened 2022-10-13 10:45 UTC
I have 3 webworker scripts that i register like   

<img width="676" alt="image" src="https://user-images.githubusercontent.com/3810177/195528327-fc4068da-e147-4b88-964e-2bfbd0c2a46b.png">

from the worker itself i can call postMessage to send a message 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/3810177/195528766-adb01be3-22d1-4610-a855-ef3e27031b44.png">

I can then listen to the webworker's message like this
<img width="521" alt="image" src="https://user-images.githubusercontent.com/3810177/195528488-3b076bfe-1c20-48f0-9788-414f95c46177.png">

Is partytown able to handle this kind of stuff?
From the documentation , I am not so certain. 

I am currently using https://www.npmjs.com/package/worker-plugin

Any clarifications on the matter is deeply appreciated.

Would be really nice to know how to postMessage to worker and vice versa.

**Comment by adamdbradley** [comment] 2023-03-21 15:19
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.

**Closed by adamdbradley** 2023-03-21 15:19 UTC
